apiVersion: 1

datasources:
  - name: SQLServer Monitoring PostgreSQL
    type: postgres
    access: proxy
    orgId: 1

    url: localhost:5432
    user: grafana_reader
    database: monitoring_db

    isDefault: true
    editable: false

    secureJsonData:
      password: YOUR_GRAFANA_READER_PASSWORD

    jsonData:
      sslmode: disable
      timescaledb: false
      timeInterval: 5m
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
